Repository global-platform/selfservice-account, pull requests merged in 2021-08, with the labels that each got.

#77 chore(deps): update terraform aws to v3.53.0
  terraform.tf
Labels: size/XS, ✅ Approved

#80 chore(deps): update terraform aws to v3.54.0
  terraform.tf
Labels: 🔍 Ready for Review, size/XS, ✅ Approved

#79 chore(deps): update terraform github.com/global-devops-terraform/user-roles to v1.18.0
  roles.tf
Labels: size/XS

#81 chore(deps): update terraform vault to v2.23.0
  terraform.tf
Labels: 🔍 Ready for Review, size/XS

#82 chore(deps): update terraform github.com/global-devops-terraform/user-roles to v1.19.0
  roles.tf
Labels: size/XS, ✅ Approved

#83 chore(deps): update terraform github.com/global-devops-terraform/user-roles to v1.20.0
  roles.tf
Labels: size/XS, ✅ Approved

#84 chore(deps): update terraform aws to v3.55.0
  terraform.tf
Labels: size/XS, ✅ Approved

#85 feat: create ecr repo
  .github/CODEOWNERS
  ecr.tf
Labels: ✅ Approved, size/L

#86 feat: Sync code
  .github/CODEOWNERS
  .github/DESCRIPTION.md
  .gitignore
  Jenkinsfile
  README.md
  dns.tf
  outputs.tf
  roles.tf
  terraform.tf
  terraform.tfvars
  variables.tf
  vars/live.tfvars
  vault.tf
Labels: 🔍 Ready for Review, size/L

#87 chore(deps): update terraform github.com/global-devops-terraform/global-info to v0.49.0
  common.tf
Labels: size/XS, ✅ Approved

#89 chore(deps): update terraform aws to v3.56.0
  terraform.tf
Labels: size/XS, ✅ Approved
