Repository global-platform/selfservice-account, pull requests merged in 2021-09, with the labels that each got.

#90 chore(deps): update terraform aws to v3.57.0
  terraform.tf
Labels: size/XS, ✅ Approved

#91 chore(deps): update terraform aws to v3.58.0
  terraform.tf
Labels: 🔍 Ready for Review, size/XS, ✅ Approved

#92 chore(deps): update terraform terraform-aws-modules/iam/aws to ~> 4.4.0
  vault.tf
Labels: 🔍 Ready for Review

#93 chore(deps): update terraform github.com/global-devops-terraform/user-roles to v1.22.0
  roles.tf
Labels: size/XS, ✅ Approved

#88 chore(deps): update terraform azuread to v2
  README.md
  roles.tf
  terraform.tf
Labels: ✅ Approved, size/M

#99 feat: create hourly cron job
  Jenkinsfile
Labels: size/XS, ✅ Approved

#97 chore(deps): update terraform aws to v3.59.0
  terraform.tf
Labels: size/XS, ✅ Approved

#96 chore(deps): update terraform terraform-aws-modules/iam/aws to ~> 4.5.0
  vault.tf
Labels: 🔍 Ready for Review, size/XS

#94 chore(deps): update terraform vault to v2.24.0
  terraform.tf
Labels: 🔍 Ready for Review, size/XS, ✅ Approved

#98 chore(deps): update terraform azuread to v2.3.0
  terraform.tf
Labels: 🔍 Ready for Review, size/XS

#95 chore(deps): update terraform github.com/global-devops-terraform/global-info to v0.50.0
  common.tf
Labels: 🔍 Ready for Review, size/XS, ✅ Approved

#101 chore(deps): update terraform terraform-aws-modules/iam/aws to ~> 4.6.0
  vault.tf
Labels: 🔍 Ready for Review, size/XS, ✅ Approved

#100 chore(deps): update terraform github.com/global-devops-terraform/user-roles to v1.24.0
  roles.tf
Labels: size/XS, ✅ Approved
