Repository global-platform/selfservice-account, pull requests merged in 2021-07, with the labels that each got.

#68 chore(deps): update terraform github.com/global-devops-terraform/user-roles to v1.14.0
  roles.tf
Labels: size/XS, 🔍 Ready for Review

#70 fix: add azure ad provider config
  provider.tf
  roles.tf
  secrets.tf
  terraform.tf
Labels: ✅ Approved

#71 chore(deps): update terraform aws to v3.50.0
  terraform.tf
Labels: ✅ Approved, 🔍 Ready for Review

#73 chore(deps): update terraform aws to v3.51.0
  terraform.tf
Labels: size/XS, ✅ Approved

#72 chore(deps): update terraform vault to v2.22.0
  terraform.tf
Labels: size/XS, 🔍 Ready for Review

#74 chore(deps): update terraform vault to v2.22.1
  terraform.tf
Labels: size/XS, ✅ Approved

#75 chore(deps): update terraform github.com/global-devops-terraform/user-roles to v1.16.1
  roles.tf
Labels: size/XS, ✅ Approved

#76 chore(deps): update terraform aws to v3.52.0
  terraform.tf
Labels: size/XS, ✅ Approved
